version: '3.8'

services:
  nginx:
    image: nginx:latest
    networks:
      - shared-network
    container_name: bashkirhaiku-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html/:/usr/share/nginx/html/:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./nginx/ssl/privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: unless-stopped

networks:
  shared-network:
    external: true